version: 2
jobs:
  test-android:
    docker:
      - image: circleci/android:api-28-node

    environment:
      JVM_OPTS: -Xmx3200m

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm run ci:build
      - run: npm run ci:lint:ts
      - run: npm run ci:lint:kotlin
      - run: npm run ci:compile:android

      - persist_to_workspace:
          root: .
          paths:
            - dist/*

  test-ios:
    macos:
      xcode: "10.3.0"
    working_directory: /Users/distiller/project

    steps:
      - checkout

      - run: sudo gem install cocoapods
      - run: npm run ci:build
      - run: cd MSCExample && npm run install:pods
      - run: npm run ci:lint:swift
      - run: npm run ci:compile:ios

  publish:
    docker:
      - image: circleci/node:10.10

    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  test:
    jobs:
      - test-android:
          filters:
            tags:
              only: /.*/

      - test-ios:
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - test-android
            - test-ios
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
